<div class="wrap">
    <h1><?=$titulo?></h1>
    <div class="section panel">
        <form method="post" enctype="multipart/form-data" action="options.php" autocomplete="off">
            <?php settings_fields($this->setting_group);?>
            <?php do_settings_sections($this->menu_slug);?>
            <p class="submit">
                <input type="submit" class="button-primary" value="<?php _e('Save Changes') ?>" />
                <a href="#TB_inline?width=320&height=300&inlineId=my-content-id" class="thickbox button-secondary" id="test-config"><?=__('Probar Configuración',WTTAPI_DOMAIN)?></a>
            </p>
        </form>
    </div>
</div>
<?php add_thickbox(); ?>
<div id="my-content-id" style="display:none;">
    <h3><?=__('Respuesta Cruda del Test',WTTAPI_DOMAIN)?></h3>
    <p><?=__('El test se esta ejecutando...',WTTAPI_DOMAIN)?></p>
</div>
<script type="text/javascript">
(function($){
    $(document).ready(function(){
        $('#test-config').click(function(){
            $.get(
                ajaxurl,
                {action:'get_timeline'},
                function(rsp){$("#TB_ajaxContent p").text(rsp);},
                'text'
            )
            .fail(function() {
                $("#TB_ajaxContent p").text("<?=__('¡Ha ocurrido un error inesperado!',WTTAPI_DOMAIN)?>");
            });
        });
    });
})(jQuery)
</script>