<aside id="wtta-widget" class="widget">
    <div id="wtwitter-root">
        <div class="wtwitter-timeline-header"></div>
        <div class="wtwitter-timeline-stream">
            <ol></ol>
        </div>
        <div class="wtwitter-timeline-footer"></div>
    </div>
<!-- <div id="mppi-twitter">
    <div>
        <small>{{usuario}}</small>
        <strong>{{nombre}}</strong>
    </div>
    <ul>
    <?php foreach ($tweets as $tweet):?>
        <li>
            <div>
                <div class="tweet">
                    <div class="cabecera">
                        <span><img src="{{img}}"></span>
                        <small>{{tiempo}}</small>
                    </div>
                    <p class="cuerpo">{{texto}}</p>
                </div>
            </div>
        </li>
    <?php endforeach;?>
    </ul>
</div>
</div>
 -->
 </aside>

<!-- <div class="header">
    <a class="u-url permalink customisable-highlight" href="https://twitter.com/cenalfilven/status/576062848457162752" data-datetime="2015-03-12T16:51:00+0000" data-scribe="element:mini_timestamp">
        <time pubdate="" class="dt-updated" datetime="2015-03-12T16:51:00+0000" title="Publicado a las: 12 mar 2015, 16:51:00 (UTC)" aria-label="Publicado hace 21  horas">
            21<abbr title=" horas">h</abbr>
        </time>
    </a>

    <div class="h-card p-author" data-scribe="component:author">
        <a class="u-url profile" href="https://twitter.com/cenalfilven" aria-label="CENAL-FILVEN (nombre de pantalla: cenalfilven)" data-scribe="element:user_link">
            <img class="u-photo avatar" alt="" src="https://pbs.twimg.com/profile_images/555809993270644736/Ch1XUgCA_normal.png" data-src-2x="https://pbs.twimg.com/profile_images/555809993270644736/Ch1XUgCA_bigger.png" data-scribe="element:avatar">
            <span class="full-name">
                <span class="p-name customisable-highlight" data-scribe="element:name">CENAL-FILVEN</span>
            </span>
            <span class="p-nickname" dir="ltr" data-scribe="element:screen_name">@<b>cenalfilven</b></span>
        </a>
    </div>

  </div> -->